steps:
    # Run tests and save to file
  - name: golang:1.18
    entrypoint: /bin/bash
    args:
      - -c
      - | 
        go test
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west6-docker.pkg.dev/micka-cloud-run-365208/demo-apps/golang-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west6-docker.pkg.dev/micka-cloud-run-365208/demo-apps/golang-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'golang-app', '--image', 'europe-west6-docker.pkg.dev/micka-cloud-run-365208/demo-apps/golang-app', '--no-traffic', '--region', 'europe-west6', '--tag', 'a$BUILD_ID']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['beta', 'run', 'services', 'update-traffic', 'golang-app', '--image', 'europe-west6-docker.pkg.dev/micka-cloud-run-365208/demo-apps/golang-app', '--to-tags', '$BUILD_ID=25']
images:
  - europe-west6-docker.pkg.dev/micka-cloud-run-365208/demo-apps/golang-app
  