steps:
    # Run tests and save to file
  - name: golang:1.18
    entrypoint: /bin/bash
    args: ['go', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west6-docker.pkg.dev/micka-cloud-run-365208/golang-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west6-docker.pkg.dev/micka-cloud-run-365208/golang-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'golang-app', '--image', 'europe-west6-docker.pkg.dev/micka-cloud-run-365208/golang-app', '--region', 'europe-west6']
images:
  - europe-west6-docker.pkg.dev/micka-cloud-run-365208/golang-app
  